name: Build training image

on: [push]

env:
  REGISTRY: ghcr.io
  BUILD_IMAGE_TAG: $(git rev-parse --short HEAD)
  LATEST_IMAGE_TAG: latest
  DEPLOY_TAG: $(git describe --tags --abbrev=0)
  DOCKER_BUILDKIT: 1
  REPO_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: chrold-train

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') != true
    permissions: write-all
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_IMAGE_TAG }} \
          --build-arg DB_HOST=${{ secrets.DATABRICKS_HOST }} \
          --build-arg DB_USERNAME=${{ secrets.DATABRICKS_USERNAME }} \
          --build-arg DB_PASS=${{ secrets.DATABRICKS_PASSWORD }} .
        docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_IMAGE_TAG }}

    - name: Push latest image
      if: github.ref_name == 'main'
      run: |
        docker tag ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_IMAGE_TAG }} ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_IMAGE_TAG }}
        docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_IMAGE_TAG }}
